### ISSUE TITLE
Differentiate select action from time travel to action

### ISSUE THREAD

**Issue by Mytrill** [hyperstart/hyperapp-devtools#4]
As of #2 selecting an action in the runs pane updates the application state.

We should differentiate between selecting an action to inspect it and time travel (i.e. update the application state) to it.

Possible implementations/UI changes:
 - a "time travel" button visible on the selected action
 - a "time travel" button visible on hover of any actions

**Comment by mrozbarry** [comment]
I guess one thing to consider is whether or not you want to care about accessibility. If you do, then we don't want a button that will only appear from mouse interaction. If you don't, or only do a little, we could do a button that shows up on `:hover` and `:focus`.

**Comment by Mytrill** [comment]
That's a good point, actually.

Maybe a button that is always visible, but only enabled when you have an action selected?

**Comment by Mytrill** [comment]
Fixed in https://github.com/hyperstart/hyperapp-devtools/commit/97d9e91280a2829268e99457c49ea884c9e8c474

@mrozbarry let me know what you think :)
